export const carModels = {
  Audi: ['A1 Sportback', 'A2', 'A3 Cabriolet', 'A4 Avant', 'A5', 'A6 Allroad', 'Q7', 'R8 Spyder', 'S5', 'TT Roadster'],
  Ford: ['Explorer', 'Kuga', 'Fiesta', 'Focus', 'Mondeo', 'EcoSport', 'Edge', 'Ranger', 'Transit', 'Galaxy'],
  Honda: ['Accord', 'Civic 4D', 'Civic 5D', 'Civic Type-R', 'CR-V', 'CrossTour', 'FR-V', 'Jazz', 'Legend', 'Pilot'],
  Hyundai: ['Accent', 'Centennial', 'Creta', 'Elantra', 'Genesis', 'Getz', 'Santa Fe', 'Solaris', 'Sonata', 'Terracan'],
  KIA: ['Carens', 'Carnival', 'Ceed', 'Cerato', 'Magentis', 'Optima', 'Picanto', 'Rio', 'Sorento', 'Soul'],
  Lada: ['Granta', 'Kalina', 'Largus', 'Niva Legend', 'Priora', 'Vesta', 'XRAY', '4x4', 'Largus Cross', 'Kalina Wagon'],
  Nissan: ['Almera', 'Juke', 'Maxima', 'Micra', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Primera', 'Terrano'],
  Porsche: [
    '718 Boxter',
    '718 Cayman',
    '911 Cabrio',
    '918 Spyder',
    'Carrera GT',
    'Cayenne',
    'Macan',
    'Panamera',
    'Panamera Sport Turismo',
    'Taycan',
  ],
  Renault: ['Arkana', 'Clio', 'Dokker', 'Duster', 'Espace', 'Kangoo', 'Kaptur', 'Logan', 'Megane', 'Sandero'],
  Toyota: ['Auris', 'Avensis', 'Camry', 'Corolla', 'Fortuner', 'Highlander', 'Hilux', 'Land Cruiser', 'Prius', 'Verso'],
  Volkswagen: [
    'Amarok',
    'Arteon',
    'Beetle',
    'Caddy',
    'California',
    'Caravelle',
    'Crafter',
    'Golf',
    'Jetta',
    'Multivan',
  ],
};
