export const Marks = [
  'Chevrolet Onyx',
  'Fiat Panda',
  'Ford Focus',
  'Ford Fusion',
  'Honda Accord',
  'Honda Civic',
  'Hyundai Accent',
  'KIA Rio',
  'Lada Largus',
  'Nissan Juke',
  'Opel',
  'Peugeot 208',
  'Porsche Cayenne',
  'Tesla',
  'Toyota Aqua',
  'Toyota Camry',
  'Toyota Corolla',
  'Toyota Land Cruiser',
  'Volkswagen Golf',
];
